-- LANTANA — seed data. Run AFTER schema.sql in the Supabase SQL editor.

insert into collections (id, slug, name, description, image) values
('col-signature','signature','{"en":"The Signature Collection","ar":"المجموعة الأصلية"}','{"en":"Eight eaux de parfum — the founding voice of the maison.","ar":"ثمانية عطور — الصوت المؤسس للدار."}','/images/products/yasmeen.jpg'),
('col-lunea','lunea-line','{"en":"The Lunéa Line","ar":"خط لونيا"}','{"en":"Our most-loved composition, in every size.","ar":"تركيبتنا الأكثر حباً، بجميع الأحجام."}','/images/products/lunea.jpg'),
('col-coffrets','coffrets','{"en":"Coffrets & Gifts","ar":"الأطقم والهدايا"}','{"en":"The discovery set — four 30 ml compositions in one case.","ar":"طقم الاكتشاف — أربع تركيبات ٣٠ مل في علبة واحدة."}','/images/products/coffret.jpg')
on conflict (id) do nothing;

insert into shipping_rates (country, label, price_usd, eta_min, eta_max) values
('SY','{"en":"Damascus & Syria — courier","ar":"دمشق وسوريا — مندوب توصيل"}',3,1,3),
('AE','{"en":"United Arab Emirates — express","ar":"الإمارات — سريع"}',12,2,4),
('SA','{"en":"Saudi Arabia — express","ar":"السعودية — سريع"}',14,3,5),
('QA','{"en":"Qatar — express","ar":"قطر — سريع"}',14,3,5),
('KW','{"en":"Kuwait — express","ar":"الكويت — سريع"}',14,3,5),
('WW','{"en":"International — DHL","ar":"دولي — DHL"}',28,5,10)
on conflict (country) do nothing;

insert into coupons (code, type, value, active, min_subtotal_usd) values
('DAMASCUS10','percent',10,true,0),
('MAISON25','fixed',25,true,200)
on conflict (code) do nothing;

insert into products (id, slug, name, tagline, description, size, concentration, collection, notes, accord, image, gallery, base_price_usd, prices, inventory, featured, hero, status) values ('p-yasmeen','yasmeen','{"en":"Yasmeen","ar":"ياسمين"}','{"en":"Damascus at first light","ar":"دمشق عند أول الضوء"}','{"en":"A bright, airy portrait of the city of jasmine. Damascene jasmine absolute opens over green mandarin and neroli, settling into a veil of white amber — luminous, weightless, unmistakably Sham.","ar":"لوحة مضيئة وهوائية لمدينة الياسمين. ياسمين دمشقي مطلق يتفتّح فوق اليوسفي الأخضر والنيرولي، ليستقر على غلالة من العنبر الأبيض — نورانيّ، خفيف، شاميّ بلا التباس."}','50 ml','Eau de Parfum','signature','{"top":[{"en":"Green mandarin","ar":"يوسفي أخضر"},{"en":"Neroli","ar":"نيرولي"}],"heart":[{"en":"Damascene jasmine","ar":"ياسمين دمشقي"},{"en":"Orange blossom","ar":"زهر البرتقال"}],"base":[{"en":"White amber","ar":"عنبر أبيض"},{"en":"Soft musk","ar":"مسك ناعم"}]}','{"en":"Solar white floral","ar":"زهري أبيض مشمس"}','/images/products/yasmeen.jpg','["/images/products/yasmeen.jpg"]',135,'{"SYP":1950000}',120,true,true,'active') on conflict (id) do nothing;
insert into products (id, slug, name, tagline, description, size, concentration, collection, notes, accord, image, gallery, base_price_usd, prices, inventory, featured, hero, status) values ('p-lunea','lunea','{"en":"Lunéa","ar":"لونيا"}','{"en":"A rose, after midnight","ar":"وردة بعد منتصف الليل"}','{"en":"Rose water and peony over a whisper of pear, drying down to white musk and sandalwood. Lunéa is the maison''s most intimate composition — a fragrance that stays closer than a secret.","ar":"ماء الورد والفاوانيا فوق همسة من الإجاص، تهدأ نحو المسك الأبيض وخشب الصندل. لونيا هي أكثر تركيبات الدار حميميةً — عطر يبقى أقرب من السر."}','50 ml','Eau de Parfum','lunea-line','{"top":[{"en":"Pear","ar":"إجاص"},{"en":"Pink berries","ar":"توت وردي"}],"heart":[{"en":"Peony","ar":"فاوانيا"},{"en":"Rose water","ar":"ماء الورد"}],"base":[{"en":"White musk","ar":"مسك أبيض"},{"en":"Sandalwood","ar":"خشب الصندل"}]}','{"en":"Powdery rose","ar":"وردي بودري"}','/images/products/lunea.jpg','["/images/products/lunea.jpg","/images/products/lunea-100.jpg"]',135,'{"SYP":1950000}',96,true,false,'active') on conflict (id) do nothing;
insert into products (id, slug, name, tagline, description, size, concentration, collection, notes, accord, image, gallery, base_price_usd, prices, inventory, featured, hero, status) values ('p-lunea-100','lunea-100','{"en":"Lunéa · 100 ml","ar":"لونيا · ١٠٠ مل"}','{"en":"The grand format","ar":"الحجم الكبير"}','{"en":"The maison''s most-loved composition in its grand 100 ml format — the same powdery rose accord, in a bottle made for the dressing table.","ar":"تركيبة الدار الأكثر حباً بحجمها الكبير ١٠٠ مل — الطابع الوردي البودري نفسه، في قارورة صُنعت لطاولة الزينة."}','100 ml','Eau de Parfum','lunea-line','{"top":[{"en":"Pear","ar":"إجاص"},{"en":"Pink berries","ar":"توت وردي"}],"heart":[{"en":"Peony","ar":"فاوانيا"},{"en":"Rose water","ar":"ماء الورد"}],"base":[{"en":"White musk","ar":"مسك أبيض"},{"en":"Sandalwood","ar":"خشب الصندل"}]}','{"en":"Powdery rose","ar":"وردي بودري"}','/images/products/lunea-100.jpg','["/images/products/lunea-100.jpg"]',190,'{"SYP":2750000}',60,false,false,'active') on conflict (id) do nothing;
insert into products (id, slug, name, tagline, description, size, concentration, collection, notes, accord, image, gallery, base_price_usd, prices, inventory, featured, hero, status) values ('p-moon','moon','{"en":"Moon","ar":"مون"}','{"en":"A nocturne in plum glass","ar":"معزوفة ليلية في زجاج بلون البرقوق"}','{"en":"Night-blooming jasmine and iris rise through bergamot and black pepper, resting on amber, musk and cedarwood. Moon is worn the way the city wears its evenings — slowly.","ar":"ياسمين الليل والسوسن يصعدان عبر البرغموت والفلفل الأسود، ليستقرا على العنبر والمسك وخشب الأرز. يُلبَس «مون» كما تلبس المدينة أمسياتها — ببطء."}','50 ml','Eau de Parfum','signature','{"top":[{"en":"Bergamot","ar":"برغموت"},{"en":"Black pepper","ar":"فلفل أسود"}],"heart":[{"en":"Night jasmine","ar":"ياسمين الليل"},{"en":"Iris","ar":"سوسن"}],"base":[{"en":"Amber","ar":"عنبر"},{"en":"Musk","ar":"مسك"},{"en":"Cedarwood","ar":"خشب الأرز"}]}','{"en":"Ambery night floral","ar":"زهري ليلي عنبري"}','/images/products/moon.jpg','["/images/products/moon.jpg"]',140,'{"SYP":2000000}',88,true,false,'active') on conflict (id) do nothing;
insert into products (id, slug, name, tagline, description, size, concentration, collection, notes, accord, image, gallery, base_price_usd, prices, inventory, featured, hero, status) values ('p-asrar','asrar','{"en":"Asrar","ar":"أسرار"}','{"en":"What the old souk remembers","ar":"ما يتذكّره السوق القديم"}','{"en":"Saffron and pink pepper open onto Damascus rose wrapped in oud smoke, grounded in leather, vanilla and patchouli. Asrar is the maison''s darkest hour — and its most magnetic.","ar":"الزعفران والفلفل الوردي يفتتحان على وردة دمشقية ملفوفة بدخان العود، ترسو على الجلد والفانيليا والباتشولي. «أسرار» هي ساعة الدار الأكثر عتمة — وجاذبية."}','50 ml','Eau de Parfum','signature','{"top":[{"en":"Saffron","ar":"زعفران"},{"en":"Pink pepper","ar":"فلفل وردي"}],"heart":[{"en":"Damascus rose","ar":"ورد دمشقي"},{"en":"Oud smoke","ar":"دخان العود"}],"base":[{"en":"Leather","ar":"جلد"},{"en":"Vanilla","ar":"فانيليا"},{"en":"Patchouli","ar":"باتشولي"}]}','{"en":"Smoky rose oud","ar":"ورد وعود مدخّن"}','/images/products/asrar.jpg','["/images/products/asrar.jpg"]',145,'{"SYP":2100000}',74,true,false,'active') on conflict (id) do nothing;
insert into products (id, slug, name, tagline, description, size, concentration, collection, notes, accord, image, gallery, base_price_usd, prices, inventory, featured, hero, status) values ('p-layal','layal','{"en":"Layal","ar":"ليالي"}','{"en":"A thousand and one evenings","ar":"ألف مساء ومساء"}','{"en":"Plum and cardamom melt into Turkish rose and violet, over a long, warm base of oud, tonka and benzoin. Layal lingers like conversation on a Damascene rooftop.","ar":"البرقوق والهيل يذوبان في الورد التركي والبنفسج، فوق قاعدة دافئة طويلة من العود والتونكا والجاوي. «ليالي» يبقى كحديثٍ على سطح دمشقي."}','50 ml','Eau de Parfum','signature','{"top":[{"en":"Plum","ar":"برقوق"},{"en":"Cardamom","ar":"هيل"}],"heart":[{"en":"Turkish rose","ar":"ورد تركي"},{"en":"Violet","ar":"بنفسج"}],"base":[{"en":"Oud","ar":"عود"},{"en":"Tonka bean","ar":"تونكا"},{"en":"Benzoin","ar":"جاوي"}]}','{"en":"Velvet oriental","ar":"شرقي مخملي"}','/images/products/layal.jpg','["/images/products/layal.jpg"]',140,'{"SYP":2000000}',82,false,false,'active') on conflict (id) do nothing;
insert into products (id, slug, name, tagline, description, size, concentration, collection, notes, accord, image, gallery, base_price_usd, prices, inventory, featured, hero, status) values ('p-barq','barq','{"en":"Barq","ar":"برق"}','{"en":"The second before rain","ar":"الثانية التي تسبق المطر"}','{"en":"An ozonic flash of grapefruit over vetiver and geranium, grounded in ambergris and oakmoss. Barq is electricity bottled — the maison''s freshest signature.","ar":"ومضة أوزونية من الجريب فروت فوق نجيل الهند وإبرة الراعي، ترسو على العنبر الرمادي وطحلب البلوط. «برق» كهرباء في قارورة — أكثر توقيعات الدار انتعاشاً."}','50 ml','Eau de Parfum','signature','{"top":[{"en":"Grapefruit","ar":"جريب فروت"},{"en":"Ozonic accord","ar":"طابع أوزوني"}],"heart":[{"en":"Vetiver","ar":"نجيل الهند"},{"en":"Geranium","ar":"إبرة الراعي"}],"base":[{"en":"Ambergris","ar":"عنبر رمادي"},{"en":"Oakmoss","ar":"طحلب البلوط"}]}','{"en":"Electric vetiver","ar":"نجيل كهربائي"}','/images/products/barq.jpg','["/images/products/barq.jpg"]',130,'{"SYP":1850000}',105,false,false,'active') on conflict (id) do nothing;
insert into products (id, slug, name, tagline, description, size, concentration, collection, notes, accord, image, gallery, base_price_usd, prices, inventory, featured, hero, status) values ('p-misk','misk','{"en":"Misk","ar":"مسك"}','{"en":"Clean as morning linen","ar":"نقيّ كالكتان الصباحي"}','{"en":"Aldehydes and lily of the valley over iris butter and white musk, finished with cashmeran and blond woods. Misk is the maison''s whisper — the scent of skin, perfected.","ar":"ألدهيدات وزنبق الوادي فوق زبدة السوسن والمسك الأبيض، بلمسة نهائية من الكشميران والأخشاب الفاتحة. «مسك» همسة الدار — رائحة البشرة في أكمل صورها."}','50 ml','Eau de Parfum','signature','{"top":[{"en":"Aldehydes","ar":"ألدهيدات"},{"en":"Lily of the valley","ar":"زنبق الوادي"}],"heart":[{"en":"White musk","ar":"مسك أبيض"},{"en":"Iris butter","ar":"زبدة السوسن"}],"base":[{"en":"Cashmeran","ar":"كشميران"},{"en":"Blond woods","ar":"أخشاب فاتحة"}]}','{"en":"White musk skin scent","ar":"مسك أبيض قريب من البشرة"}','/images/products/misk.jpg','["/images/products/misk.jpg"]',130,'{"SYP":1850000}',90,false,false,'active') on conflict (id) do nothing;
insert into products (id, slug, name, tagline, description, size, concentration, collection, notes, accord, image, gallery, base_price_usd, prices, inventory, featured, hero, status) values ('p-waqaar','waqaar','{"en":"Waqaar","ar":"وقار"}','{"en":"Presence, without a word","ar":"حضور بلا كلمة"}','{"en":"Cypress and incense open onto Taif rose and a dates accord, anchored by oud, sandalwood and labdanum in the grand 100 ml format. Waqaar enters the room before you do.","ar":"السرو والبخور يفتتحان على ورد الطائف وطابع التمر، ويرسوان على العود وخشب الصندل واللبان في الحجم الكبير ١٠٠ مل. «وقار» يدخل الغرفة قبلك."}','100 ml','Eau de Parfum','signature','{"top":[{"en":"Cypress","ar":"سرو"},{"en":"Incense","ar":"بخور"}],"heart":[{"en":"Taif rose","ar":"ورد الطائف"},{"en":"Dates accord","ar":"طابع التمر"}],"base":[{"en":"Oud","ar":"عود"},{"en":"Sandalwood","ar":"خشب الصندل"},{"en":"Labdanum","ar":"لبان"}]}','{"en":"Regal incense oud","ar":"عود وبخور ملكي"}','/images/products/waqaar.jpg','["/images/products/waqaar.jpg"]',195,'{"SYP":2800000}',45,true,false,'active') on conflict (id) do nothing;
insert into products (id, slug, name, tagline, description, size, concentration, collection, notes, accord, image, gallery, base_price_usd, prices, inventory, featured, hero, status) values ('p-coffret','discovery-coffret','{"en":"The Discovery Coffret","ar":"طقم الاكتشاف"}','{"en":"Four compositions, one case","ar":"أربع تركيبات، علبة واحدة"}','{"en":"Lunéa, Misk, Moon and Yasmeen in 30 ml formats, presented in the maison''s olive case. The complete introduction to LANTANA — and the gift we are asked for most.","ar":"لونيا، مسك، مون وياسمين بحجم ٣٠ مل، في علبة الدار الزيتونية. المدخل الكامل إلى لانتانا — والهدية الأكثر طلباً."}','4 × 30 ml','Eau de Parfum','coffrets','{"top":[{"en":"Lunéa","ar":"لونيا"},{"en":"Misk","ar":"مسك"}],"heart":[{"en":"Moon","ar":"مون"},{"en":"Yasmeen","ar":"ياسمين"}],"base":[{"en":"Presented in the olive coffret","ar":"في العلبة الزيتونية"}]}','{"en":"The maison, entire","ar":"الدار كاملةً"}','/images/products/coffret.jpg','["/images/products/coffret.jpg","/images/products/coffret-2.jpg"]',240,'{"SYP":3450000}',40,true,false,'active') on conflict (id) do nothing;
insert into blog_posts (id, slug, title, excerpt, body, image, published_at) values ('b1','the-city-of-jasmine','{"en":"The city of jasmine","ar":"مدينة الياسمين"}','{"en":"Why Damascus is the only city where LANTANA could have been born.","ar":"لماذا دمشق هي المدينة الوحيدة التي كان يمكن أن تولد فيها لانتانا."}','{"en":"Every fragrance house has an origin. Ours is a city. Damascus has perfumed the world for a thousand years — rose water from Ghouta, jasmine over every courtyard wall, oud in the covered souks. LANTANA begins where that history lives: not as nostalgia, but as raw material. Our compositions take the Levant''s memory and set it in French and Swiss essences, macerated slowly and finished by hand in Dubai. The result is not a souvenir of Damascus. It is Damascus, worn.","ar":"لكل دار عطور أصل. أصلنا مدينة. عطّرت دمشق العالم لألف عام — ماء الورد من الغوطة، والياسمين فوق كل جدار، والعود في الأسواق المسقوفة. تبدأ لانتانا حيث تعيش تلك الذاكرة: ليس حنيناً، بل مادةً خام. تأخذ تركيباتنا ذاكرة الشام وتصوغها بخلاصات فرنسية وسويسرية، تُنقَع ببطء وتُنهى يدوياً في دبي. النتيجة ليست تذكاراً من دمشق. إنها دمشق، تُلبَس."}','/images/products/yasmeen.jpg','2026-06-15T00:00:00Z') on conflict (id) do nothing;
insert into blog_posts (id, slug, title, excerpt, body, image, published_at) values ('b2','how-to-wear-eau-de-parfum','{"en":"How to wear an eau de parfum","ar":"كيف تلبس أو دو بارفان"}','{"en":"Less, placed well, lasts longer than more, placed anywhere.","ar":"القليل في المكان الصحيح يدوم أكثر من الكثير في أي مكان."}','{"en":"Two sprays. Warm points — the inner wrist, the base of the throat, behind the ear. Never rub; friction breaks the top notes before they open. Spray onto skin after moisturising, when the surface holds scent longest. And choose by hour, not occasion: bright compositions like Yasmeen belong to daylight, while Asrar and Moon are made for the evening. A fragrance worn quietly is noticed more, not less.","ar":"رشّتان. على نقاط الدفء — باطن المعصم، أسفل العنق، خلف الأذن. لا تفرك أبداً؛ الاحتكاك يكسر نوتات المقدمة قبل أن تتفتّح. رشّ على البشرة بعد الترطيب، حين تحتفظ بالعطر أطول. واختر بحسب الساعة لا المناسبة: التركيبات المضيئة مثل ياسمين لضوء النهار، بينما صُنع أسرار ومون للمساء. العطر الذي يُلبَس بهدوء يُلاحَظ أكثر، لا أقل."}','/images/products/lunea.jpg','2026-06-28T00:00:00Z') on conflict (id) do nothing;

-- Sample approved reviews
insert into reviews (product_id, author, rating, body, approved) values ('p-yasmeen','Rima K.',5,'It smells like the courtyards of the old city in June. I wear nothing else now.',true);
insert into reviews (product_id, author, rating, body, approved) values ('p-lunea','Sarah A.',5,'Soft, close to the skin, and people always ask what it is.',true);
insert into reviews (product_id, author, rating, body, approved) values ('p-asrar','Omar H.',4,'Deep and smoky without being heavy. Lasts from morning to night.',true);
